services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store_db
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8002:8000"
    networks:
      - backend

  migrate:
    build: .
    command: poetry run alembic upgrade head
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend

  redis:
    image: redis:7
    restart: always
    ports:
      - "6381:6379"
    networks:
      - backend

  celery:
    build: .
    command: poetry run celery -A app.worker.celery_app worker --loglevel=info --max-tasks-per-child=1
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - selenium
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
    networks:
      - backend

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    platform: linux/amd64
    shm_size: 2gb
    ports:
      - "4444:4444"
    networks:
      - backend

  flower:
    image: mher/flower
    restart: always
    command: celery --broker=${REDIS_URL} flower --port=5555
    environment:
      FLOWER_PORT: 5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - backend

volumes:
  pgdata:


networks:
  backend:
    driver: bridge
