"""banners promo models

Revision ID: 1f591f7a4ac7
Revises: a626a67d512f
Create Date: 2025-04-07 10:05:44.934184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f591f7a4ac7'
down_revision: Union[str, None] = 'a626a67d512f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'url')
    # ### end Alembic commands ###
