"""add brend and catalog  table

Revision ID: 24e2fa10e739
Revises: d79f0efa866a
Create Date: 2025-05-09 09:11:10.049522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e2fa10e739'
down_revision: Union[str, None] = 'd79f0efa866a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogs', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'catalogs', 'brands', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalogs', type_='foreignkey')
    op.drop_column('catalogs', 'brand_id')
    # ### end Alembic commands ###
