"""banner_show_button_expires_at

Revision ID: 2ad5b71a92ab
Revises: 44ddb90cd6c9
Create Date: 2026-03-08 17:41:26.156159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad5b71a92ab'
down_revision: Union[str, None] = '44ddb90cd6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('show_button', sa.Boolean(), nullable=True))
    op.add_column('banners', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banners', 'expires_at')
    op.drop_column('banners', 'show_button')
    # ### end Alembic commands ###
