"""add_source_url_sync_fields_to_products

Revision ID: 3d3a13ca8faf
Revises: 2ad5b71a92ab
Create Date: 2026-03-21 16:19:49.957256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3a13ca8faf'
down_revision: Union[str, None] = '2ad5b71a92ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('needs_review', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('missing_since', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_products_source_url'), 'products', ['source_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_source_url'), table_name='products')
    op.drop_column('products', 'missing_since')
    op.drop_column('products', 'last_synced_at')
    op.drop_column('products', 'needs_review')
    op.drop_column('products', 'source_url')
    # ### end Alembic commands ###
