"""add_banners

Revision ID: 44ddb90cd6c9
Revises: 9f0b379f9106
Create Date: 2026-03-07 14:19:02.845273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ddb90cd6c9'
down_revision: Union[str, None] = '9f0b379f9106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('image_url', sa.String(length=500), nullable=False))
    op.add_column('banners', sa.Column('subtitle', sa.String(length=500), nullable=True))
    op.add_column('banners', sa.Column('href', sa.String(length=500), nullable=True))
    op.add_column('banners', sa.Column('badge', sa.String(length=50), nullable=True))
    op.add_column('banners', sa.Column('text_color', sa.String(length=10), nullable=True))
    op.add_column('banners', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.add_column('banners', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('banners', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('banners', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('banners', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_banners_is_active'), 'banners', ['is_active'], unique=False)
    op.create_index(op.f('ix_banners_sort_order'), 'banners', ['sort_order'], unique=False)
    op.drop_column('banners', 'image')
    op.drop_column('banners', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('banners', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_banners_sort_order'), table_name='banners')
    op.drop_index(op.f('ix_banners_is_active'), table_name='banners')
    op.alter_column('banners', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('banners', 'updated_at')
    op.drop_column('banners', 'created_at')
    op.drop_column('banners', 'is_active')
    op.drop_column('banners', 'sort_order')
    op.drop_column('banners', 'text_color')
    op.drop_column('banners', 'badge')
    op.drop_column('banners', 'href')
    op.drop_column('banners', 'subtitle')
    op.drop_column('banners', 'image_url')
    # ### end Alembic commands ###
