"""remove_manufacturer_from_categories

Revision ID: 52bf79b4691c
Revises: 748184b27c4c
Create Date: 2025-05-29 08:23:22.000248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bf79b4691c'
down_revision: Union[str, None] = '748184b27c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_brand_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'brand_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('categories_brand_id_fkey', 'categories', 'brands', ['brand_id'], ['id'])
    # ### end Alembic commands ###
