"""video table

Revision ID: 6592dfcb0f85
Revises: ef7e54dd6362
Create Date: 2025-05-02 20:01:07.835160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6592dfcb0f85'
down_revision: Union[str, None] = 'ef7e54dd6362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('product_slug', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('detection_confidence', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('auto_detected', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_videos_product_slug'), 'videos', ['product_slug'], unique=False)
    op.drop_constraint('videos_catalog_id_fkey', 'videos', type_='foreignkey')
    op.drop_constraint('videos_category_id_fkey', 'videos', type_='foreignkey')
    op.drop_column('videos', 'catalog_id')
    op.drop_column('videos', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('catalog_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('videos_category_id_fkey', 'videos', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('videos_catalog_id_fkey', 'videos', 'catalogs', ['catalog_id'], ['id'])
    op.drop_index(op.f('ix_videos_product_slug'), table_name='videos')
    op.drop_column('videos', 'auto_detected')
    op.drop_column('videos', 'detection_confidence')
    op.drop_column('videos', 'product_slug')
    # ### end Alembic commands ###
