"""rank table

Revision ID: 748184b27c4c
Revises: d7234108921e
Create Date: 2025-05-13 20:31:41.409982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748184b27c4c'
down_revision: Union[str, None] = 'd7234108921e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ranking_score', sa.Float(), nullable=True),
    sa.Column('admin_score', sa.Float(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('priority_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seasonal_relevance', sa.JSON(), nullable=True),
    sa.Column('category_boost', sa.Float(), nullable=True),
    sa.Column('impressions_count', sa.Integer(), nullable=True),
    sa.Column('last_recalculated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('product_type_multiplier', sa.Float(), nullable=True),
    sa.Column('stock_status_multiplier', sa.Float(), nullable=True),
    sa.Column('price_range_multiplier', sa.Float(), nullable=True),
    sa.Column('custom_tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_product_rankings_id'), 'product_rankings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_rankings_id'), table_name='product_rankings')
    op.drop_table('product_rankings')
    # ### end Alembic commands ###
