"""analistic table

Revision ID: 74cc02eeeb79
Revises: ef34cca97179
Create Date: 2025-06-04 08:01:23.567657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74cc02eeeb79'
down_revision: Union[str, None] = 'ef34cca97179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_daily_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('detail_views_count', sa.Integer(), nullable=True),
    sa.Column('interactions_count', sa.Integer(), nullable=True),
    sa.Column('unique_sessions', sa.Integer(), nullable=True),
    sa.Column('avg_view_duration', sa.Integer(), nullable=True),
    sa.Column('total_view_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_date', 'analytics_daily_summary', ['product_id', 'date'], unique=False)
    op.create_index(op.f('ix_analytics_daily_summary_date'), 'analytics_daily_summary', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_daily_summary_id'), 'analytics_daily_summary', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_daily_summary_product_id'), 'analytics_daily_summary', ['product_id'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_subtype', sa.String(length=50), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('page_url', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_event_date', 'analytics_events', ['product_id', 'event_type', 'created_at'], unique=False)
    op.create_index('idx_session_date', 'analytics_events', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_subtype'), 'analytics_events', ['event_subtype'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_id'), 'analytics_events', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_events_product_id'), 'analytics_events', ['product_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.create_table('analytics_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('first_page', sa.Text(), nullable=True),
    sa.Column('last_page', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=True),
    sa.Column('products_viewed', sa.Integer(), nullable=True),
    sa.Column('interactions_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_sessions_id'), 'analytics_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_sessions_last_activity'), 'analytics_sessions', ['last_activity'], unique=False)
    op.create_index(op.f('ix_analytics_sessions_session_id'), 'analytics_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_analytics_sessions_started_at'), 'analytics_sessions', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_sessions_started_at'), table_name='analytics_sessions')
    op.drop_index(op.f('ix_analytics_sessions_session_id'), table_name='analytics_sessions')
    op.drop_index(op.f('ix_analytics_sessions_last_activity'), table_name='analytics_sessions')
    op.drop_index(op.f('ix_analytics_sessions_id'), table_name='analytics_sessions')
    op.drop_table('analytics_sessions')
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_product_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_subtype'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    op.drop_index('idx_session_date', table_name='analytics_events')
    op.drop_index('idx_product_event_date', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_analytics_daily_summary_product_id'), table_name='analytics_daily_summary')
    op.drop_index(op.f('ix_analytics_daily_summary_id'), table_name='analytics_daily_summary')
    op.drop_index(op.f('ix_analytics_daily_summary_date'), table_name='analytics_daily_summary')
    op.drop_index('idx_product_date', table_name='analytics_daily_summary')
    op.drop_table('analytics_daily_summary')
    # ### end Alembic commands ###
