"""video add

Revision ID: 7939ec847f5b
Revises: bb54689b1f10
Create Date: 2025-04-28 15:29:54.430762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7939ec847f5b'
down_revision: Union[str, None] = 'bb54689b1f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalogs', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('categories', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('categories', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('catalogs', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
