"""video add

Revision ID: 9c849f61221d
Revises: 4ddf1214cf9c
Create Date: 2025-04-28 14:40:15.551553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c849f61221d'
down_revision: Union[str, None] = '4ddf1214cf9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalogs', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('categories', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('videos', sa.Column('catalog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'videos', 'catalogs', ['catalog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'catalog_id')
    op.alter_column('products', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('categories', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('catalogs', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
