"""add local image fields to product_images

Revision ID: 9f0b379f9106
Revises: f53896e87feb
Create Date: 2026-02-28 09:16:40.424825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0b379f9106'
down_revision: Union[str, None] = 'f53896e87feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('original_url', sa.String(), nullable=True))
    op.add_column('product_images', sa.Column('is_local', sa.Boolean(), nullable=True))
    op.add_column('product_images', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('product_images', sa.Column('download_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'download_error')
    op.drop_column('product_images', 'file_size')
    op.drop_column('product_images', 'is_local')
    op.drop_column('product_images', 'original_url')
    # ### end Alembic commands ###
