"""video table

Revision ID: cdbff6a7c6b3
Revises: 52bf79b4691c
Create Date: 2025-05-30 13:29:57.695100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdbff6a7c6b3'
down_revision: Union[str, None] = '52bf79b4691c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_color')
    op.drop_index('ix_colors_id', table_name='colors')
    op.drop_table('colors')
    op.drop_constraint('categories_parent_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    op.drop_index('ix_videos_product_slug', table_name='videos')
    op.drop_column('videos', 'detection_confidence')
    op.drop_column('videos', 'product_slug')
    op.drop_column('videos', 'auto_detected')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('auto_detected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('product_slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('detection_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index('ix_videos_product_slug', 'videos', ['product_slug'], unique=False)
    op.add_column('categories', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('categories_parent_id_fkey', 'categories', 'categories', ['parent_id'], ['id'], ondelete='SET NULL')
    op.create_table('colors',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('colors_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='colors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_colors_id', 'colors', ['id'], unique=False)
    op.create_table('product_color',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name='product_color_color_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_color_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'color_id', name='product_color_pkey')
    )
    # ### end Alembic commands ###
