"""product fix  models

Revision ID: d757a0b3ce21
Revises: 3d5e82b4c355
Create Date: 2025-04-06 07:35:29.394153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd757a0b3ce21'
down_revision: Union[str, None] = '3d5e82b4c355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('is_main', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'is_main')
    # ### end Alembic commands ###
