"""add oauth fields and sessions

Revision ID: e256a31c763e
Revises: cca5f5a29024
Create Date: 2025-06-02 16:09:56.055691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e256a31c763e'
down_revision: Union[str, None] = 'cca5f5a29024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('author_email', sa.String(length=255), nullable=True))
    op.add_column('reviews', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('reviews', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('reviews', 'author_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint('reviews_product_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'])
    op.drop_column('reviews', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_product_id_fkey', 'reviews', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reviews', 'author_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('reviews', 'is_active')
    op.drop_column('reviews', 'comment')
    op.drop_column('reviews', 'title')
    op.drop_column('reviews', 'author_email')
    # ### end Alembic commands ###
