"""product table

Revision ID: fa55086ad251
Revises: 43a9080c6764
Create Date: 2025-04-25 10:29:55.530576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa55086ad251'
down_revision: Union[str, None] = '43a9080c6764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalogs', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('categories', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('categories_manufacturer_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'brands', ['brand_id'], ['id'])
    op.drop_column('categories', 'manufacturer_id')
    op.alter_column('products', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('categories', sa.Column('manufacturer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_manufacturer_id_fkey', 'categories', 'manufacturers', ['manufacturer_id'], ['id'])
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('categories', 'brand_id')
    op.alter_column('catalogs', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
